server:
  port: 9001

security:
  oauth2:
    client:
      client-id: merryyou1
      client-secret: merryyousecrect1
      user-authorization-uri: http://127.0.0.1:8401/oauth/authorize #请求认证的地址
      access-token-uri: http://127.0.0.1:8401/oauth/token #请求令牌的地址
    resource:
      jwt:
        key-uri: http://127.0.0.1:8401/oauth/token_key #解析jwt令牌所需要密钥的地址