spring:
  application:
    name: @pom.artifactId@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId (大写) 创建路由的功能。

server:
  port: 8322
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8321/eureka
# 目前 Hystrix Command 执行超时时，返回客户端 504 状态码，
# 如果使用 JSON 格式作为数据返回，则需要修改下该 HystrixGatewayFilter 的代码实现。
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
